### ISSUE TITLE
Latest develop build throws an exception about JSON

### ISSUE THREAD

**Issue by Zverik** [Zettlr/Zettlr#1353]
I have just checked out the develop version of Zettlr (f1c5c2f762676d3a0f7ff20d366ad6034eb1c03c). When starting, it prints no errors to the console, but this error dialog appears:

![zettlr-json-error](https://user-images.githubusercontent.com/766031/96292627-2c059e00-0ff2-11eb-87c2-bde5839ed047.png)

After I press "ok", it shows the main window and a sidebar with files, but there is no content for open notes, and I cannot choose any files on the sidebar (but can change directories).

**Comment by Zverik** [comment]
It also printed an error on shutdown:

```
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'children' -> object with constructor 'Array'
    |     index 0 -> object with constructor 'Object'
    --- property 'parent' closes the circle
    at JSON.stringify (<anonymous>)
    at ConfigProvider.save (/home/zverik/progr/git/Zettlr/.webpack/main/index.js:115942:44)
    at Object.save (/home/zverik/progr/git/Zettlr/.webpack/main/index.js:115842:26)
    at Zettlr.<anonymous> (/home/zverik/progr/git/Zettlr/.webpack/main/index.js:120255:39)
    at step (/home/zverik/progr/git/Zettlr/.webpack/main/index.js:119942:23)
    at Object.next (/home/zverik/progr/git/Zettlr/.webpack/main/index.js:119923:53)
    at /home/zverik/progr/git/Zettlr/.webpack/main/index.js:119917:71
    at new Promise (<anonymous>)
    at module.exports../source/main/zettlr.ts.__awaiter (/home/zverik/progr/git/Zettlr/.webpack/main/index.js:119913:12)
    at Zettlr.module.exports../source/main/zettlr.ts.Zettlr.shutdown (/home/zverik/progr/git/Zettlr/.webpack/main/index.js:120246:16)
Error during will-quit event shutdown TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'children' -> object with constructor 'Array'
    |     index 0 -> object with constructor 'Object'
    --- property 'parent' closes the circle
    at JSON.stringify (<anonymous>)
    at ConfigProvider.save (/home/zverik/progr/git/Zettlr/.webpack/main/index.js:115942:44)
    at Object.save (/home/zverik/progr/git/Zettlr/.webpack/main/index.js:115842:26)
    at Zettlr.<anonymous> (/home/zverik/progr/git/Zettlr/.webpack/main/index.js:120255:39)
    at step (/home/zverik/progr/git/Zettlr/.webpack/main/index.js:119942:23)
    at Object.next (/home/zverik/progr/git/Zettlr/.webpack/main/index.js:119923:53)
    at /home/zverik/progr/git/Zettlr/.webpack/main/index.js:119917:71
    at new Promise (<anonymous>)
    at module.exports../source/main/zettlr.ts.__awaiter (/home/zverik/progr/git/Zettlr/.webpack/main/index.js:119913:12)
    at Zettlr.module.exports../source/main/zettlr.ts.Zettlr.shutdown (/home/zverik/progr/git/Zettlr/.webpack/main/index.js:120246:16)
```

**Comment by nathanlesage** [comment]
Might be. I ripped apart the whole FSAL again, and this will be a hefty commit. Due to moving I have to split up the work in multiple days, and I'm not as fast as I want to be. Sorry for that. Benefit of waiting: I'm currently testing the hell out of the FSAL, and the migration to TypeScript enables me to perform a lot of optimizations, so after I'm done it should make a lot more sense to others AND have a lot less bugs 👌🏼

**Comment by nathanlesage** [comment]
(Btw the error you encounter is due to the real file tree being sent, instead of the metadata, which is likely as I committed a few things before I decided to make a big commit, hence the buggy code)

**Comment by nathanlesage** [comment]
Just pushed all commits, it should work again, now!

**Comment by Zverik** [comment]
It works — thank you!
