### ISSUE TITLE
[Regression] Javascript error on trying to open .md file if Zettlr is already open

### ISSUE THREAD

**Issue by the-solipsist** [Zettlr/Zettlr#1436]
## Description

If Zettlr is already open, opening a file (for a format which Zettlr is designated as the default handler) from the file manager fails.

If Zettlr isn't already open, doing so works.

The error I get is:

**A JavaScript error occurred in the main process.**
Uncaught Exception:
TypeError: Cannot read property 'length' of undefined 
  at App.<anonymous>(/opt/Zettlr/resources/app.asar/.webpack/-main/index.js:47:158574)
  at App.emit (events.js:310:20)

## Reproducing

1. Open Zettlr
2. Open Nautilus / your favourite file manager and navigate to a `.md` file.
3. Double click on that `.md` file.

## Expected behaviour

It should open the file in a new tab in Zettlr.

![image](https://user-images.githubusercontent.com/3080824/99658241-38639780-2a85-11eb-9165-f349568b2227.png)

## Platform
 - OS and version: Ubuntu 20.10 (5.8.0-28-generic x86_64)
 - Zettlr Version: 1.8beta4

**Comment by the-solipsist** [comment]
This error might be fixed by https://github.com/Zettlr/Zettlr/commit/73511008d7f230cb856593ace829b0be75ad1ddb. Closing this issue. 

It can be reopened in case it isn't fixed.
