### ISSUE TITLE
[1.8.0] Can't package without internet connection

### ISSUE THREAD

**Issue by Marko10-000** [Zettlr/Zettlr#1487]
## Description
I try to package Zettlr 1.8.0 in flatpak. Unfortunately there is a bug with requires to always download electron on the package stage in yarn from github and doesn't use the cached version like in the install stage in yarn.This is crucial for a deterministic build else I have to try to fake the Github server.

## Reproducing
```bash
git clone https://git.marko10-000.de/flatpaks/flatpak.git &&
cd flatpak &&
git checkout dev &&
cd com.zettlr.Zettlr &&
flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo &&
flatpak-builder --user --install-deps-from=flathub --force-clean build com.zettlr.Zettlr.yaml
```

## Expected behaviour
Use cached version of electron.

## Platform
 - OS and version: Linux – Freedesktop SDK 20.08
 - Zettlr Version: 1.8.0 (tarball) 

## Additional information
Console output:
```
========================================================================
Building module zettlr in /home/marko/tmp/.flatpak-builder/build/zettlr-18
========================================================================
Running: yarn --offline config set yarn-offline-mirror "$(pwd)/flatpak-node/yarn-mirror" && export electron_config_cache="$(pwd)"/flatpak-node/electron-cache && cd zettlr && yarn --offline install && yarn --offline package
yarn config v1.22.10
success Set "yarn-offline-mirror" to "/run/build/zettlr/flatpak-node/yarn-mirror".
Done in 0.02s.
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.2: The platform "linux" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > @clr/icons@4.0.4" has unmet peer dependency "@webcomponents/custom-elements@^1.0.0".
warning " > copy-webpack-plugin@6.1.0" has unmet peer dependency "webpack@^4.37.0 || ^5.0.0".
warning " > css-loader@3.6.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning " > eslint-loader@4.0.2" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning " > file-loader@6.1.1" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning " > less-loader@7.0.2" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning " > node-loader@1.0.2" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning " > raw-loader@4.0.2" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning " > style-loader@1.2.1" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning " > vue-loader@15.9.3" has unmet peer dependency "webpack@^3.0.0 || ^4.1.0 || ^5.0.0-0".
[4/4] Building fresh packages...
$ electron-builder install-app-deps
  • electron-builder  version=22.8.0
  • loaded configuration  file=package.json ("build" field)
Done in 37.78s.
yarn run v1.22.10
$ electron-forge package
✔ Checking your system
✔ Compiling Main Process Code
✔ Compiling Renderer Template
⠼ Preparing to Package Application for arch: x64
An unhandled rejection has occurred inside Forge:
GotError [RequestError]: getaddrinfo EAI_AGAIN github.com
    at ClientRequest.<anonymous> (/run/build/zettlr/zettlr/node_modules/@electron/get/node_modules/got/source/request-as-event-emitter.js:178:14)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.origin.emit (/run/build/zettlr/zettlr/node_modules/@electron/get/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'EAI_AGAIN',
  host: 'github.com',
  hostname: 'github.com',
  method: 'GET',
  path: '/electron/electron/releases/download/v10.1.5/electron-v10.1.5-linux-x64.zip',
  socketPath: undefined,
  protocol: 'https:',
  url: 'https://github.com/electron/electron/releases/download/v10.1.5/electron-v10.1.5-linux-x64.zip',
  gotOptions: {
    path: '/electron/electron/releases/download/v10.1.5/electron-v10.1.5-linux-x64.zip',
    protocol: 'https:',
    slashes: true,
    auth: null,
    host: 'github.com',
    port: null,
    hostname: 'github.com',
    hash: null,
    search: null,
    query: null,
    pathname: '/electron/electron/releases/download/v10.1.5/electron-v10.1.5-linux-x64.zip',
    href: 'https://github.com/electron/electron/releases/download/v10.1.5/electron-v10.1.5-linux-x64.zip',
    retry: {
      retries: [Function (anonymous)],
      methods: [Set],
      statusCodes: [Set],
      errorCodes: [Set]
    },
    headers: {
      'user-agent': 'got/9.6.0 (https://github.com/sindresorhus/got)',
      'accept-encoding': 'gzip, deflate'
    },
    hooks: {
      beforeRequest: [],
      beforeRedirect: [],
      beforeRetry: [],
      afterResponse: [],
      beforeError: [],
      init: []
    },
    decompress: true,
    throwHttpErrors: true,
    followRedirect: true,
    stream: true,
    form: false,
    json: false,
    cache: false,
    useElectronNet: false,
    method: 'GET'
  }
}

Electron Forge was terminated. Location:
{}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: module zettlr: Der Kindprozess wurde mit Status 1 beendet
```

**Comment by nathanlesage** [comment]
As your error log output clearly states:

> An unhandled rejection has occurred inside Forge:

Ergo: This is not the right repository, please report this to the people from electron-forge. Thanks!
