### ISSUE TITLE
[FEATURE] Build for armv7l (Raspberry Pi 32 bits)

### ISSUE THREAD

**Issue by benpro** [Zettlr/Zettlr#1639]
I would like to use Zettlr on my Raspberry 4 which run Raspbian OS. Raspbian OS runs in 32 bits mode.
Can you build and release next versions for armv7l?
In the meantime I will look to build it myself, but building on a Pi could take a while...

**Comment by nathanlesage** [comment]
Thank you for your issue! Unfortunately, as laid out in issue #1552, we have just deprecated 32 bit support, so you would have to build it on your own. This works by downloading the source according to the Readme, and then running both `electron-forge` and (if you want a distributable package) `electron-builder` with the specified settings, which you can find on the corresponding homepages!

**Comment by benpro** [comment]
Alas it doesn't works.

```
$ npm start

> zettlr@1.8.6 start /home/benpro/devel/Zettlr
> electron-forge start

✔ Checking your system

An unhandled exception has occurred inside Forge:
Cannot find module 'electron-packager/targets'
Require stack:
- /home/benpro/devel/Zettlr/node_modules/electron-forge/dist/api/make.js
- /home/benpro/devel/Zettlr/node_modules/electron-forge/dist/api/index.js
- /home/benpro/devel/Zettlr/node_modules/electron-forge/dist/electron-forge-start.js
Error: Cannot find module 'electron-packager/targets'
Require stack:
- /home/benpro/devel/Zettlr/node_modules/electron-forge/dist/api/make.js
- /home/benpro/devel/Zettlr/node_modules/electron-forge/dist/api/index.js
- /home/benpro/devel/Zettlr/node_modules/electron-forge/dist/electron-forge-start.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/benpro/devel/Zettlr/node_modules/electron-forge/dist/api/make.js:27:16)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/benpro/devel/Zettlr/node_modules/electron-forge/dist/api/index.js:21:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)

```

**Comment by benpro** [comment]
May be related to https://www.electronjs.org/blog/linux-32bit-support ...

**Comment by nathanlesage** [comment]
Yep, that might be – sorry :/
