### ISSUE TITLE
Latest development build does not start in Linux

### ISSUE THREAD

**Issue by Zverik** [Zettlr/Zettlr#1644]
I have updated the `develop` branch to commit 9246a00578c96517a0df26365c4a7f6d717beea4. Now Zettlr prints common startup lines, but exits in the end with no reasonable error message. It looks like this:

```
[23:29:07] こんにちは！ Booting Zettlr at Sun Jan 17 2021 23:29:07 GMT+0300 (Москва, стандартное время).
[23:29:07] Performing environment check ...
[23:29:07] [Application] App is unpackaged, but there was no Pandoc executable: /home/zverik/progr/git/Zettlr/resources/pandoc
[23:29:07] Environment check complete.
[23:29:07] Registering custom protocol safe-file
[23:29:07] Log provider booting up ...
[23:29:07] Config provider booting up ...
[23:29:07] [Config Provider] Loading configuration file from /home/zverik/.config/Zettlr/config.json ...
[23:29:07] [Config Provider] Successfully loaded configuration
[23:29:07] Appearance provider booting up ...
[23:29:07] Citeproc provider booting up ...
[23:29:07] [Citeproc Provider] There is no CSL library selected in the preferences. Nothing to do.
[23:29:07] Dictionary provider booting up ...
[23:29:07] Recent documents provider booting up ...
[23:29:07] Tag provider booting up ...
[23:29:07] Target provider booting up
[23:29:07] CSS provider booting up ...
[23:29:07] Translation provider booting up ...
[23:29:07] Update provider booting up ...
[23:29:07] Notification provider booting up ...
[23:29:07] Stats provider booting up
[23:29:07] FSAL booting up ...
[23:29:07] Loaded all roots in 0.002 seconds
Done in 15.85s.
[zverik@localhost Zettlr]$ 
[zverik@localhost Zettlr]$ (node:823102) UnhandledPromiseRejectionWarning: RpcIpcMessagePortClosedError: Cannot send the message - the message port has been closed for the process 823102.
    at /home/zverik/progr/git/Zettlr/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/rpc-ipc/RpcIpcMessagePort.js:47:47
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
(node:823102) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:823102) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Note the command line prompt after the `Done in 15 s` line.

My OS is Fedora Linux 32

Building from the `v1.8.6` tag, the app started well. The last part of the log before the window has opened looked like this:

```
[23:52:58] FSAL booting up ...
[23:52:58] Loaded all roots in 0.002 seconds
[23:52:58] [Update Provider] Checking for application updates ...
(node:823904) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
[23:52:58] [Update Provider] No new update available. Current version is v1.8.6.
webpack built 0e867f543353087d720b in 18497ms
No issues found.
[23:53:17] [R] [Main Window] You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html (index.js:207927)
[23:53:17] [R] [Main Window] [HMR] connected (index.js:209414)
```

**Comment by nathanlesage** [comment]
It can very well be, that the current HEAD of develop is unrunnable. I've ripped apart quite a few things, and just committed these. I'm sure it's going to work again after a few more commits. There are three big construction sites and right now I don't know which one I want to start with …

**Comment by tony** [comment]
Has anyone got to the root of this?

`node -v`?  Is this on linux? macs? CI?

**Comment by Kangie** [comment]
@tony, this is because the code at the head of develop is not always stable. 

Sometimes commits to the repo result in build failures that may take another few commits to resolve.
