### ISSUE TITLE
Exception when trying to open empty file

### ISSUE THREAD

**Issue by dometto** [Zettlr/Zettlr#180]
## Description

I initialized an empty file on the command line with `touch`, then wanted to open this with Zettlr. This caused an exception to be raised (error dialog pops up).

## Reproducing

1. `touch test.md`
2. Open `test.md` (on OS X, via the Finder, right click and 'Open With >')

## Expected behaviour

The file opens.

## Error message

```
Uncaught Exception:
TypeError: Cannot read property 'setTitle' of null
    at ZettlrWindow.setTitle (/Applications/Zettlr.app/Contents/Resources/app.asar/main/zettlr-window.js:207:15)
    at ZettlrWindow.fileUpdate (/Applications/Zettlr.app/Contents/Resources/app.asar/main/zettlr-window.js:220:12)
    at Zettlr.setCurrentFile (/Applications/Zettlr.app/Contents/Resources/app.asar/main/zettlr.js:606:34)
    at Zettlr.sendFile (/Applications/Zettlr.app/Contents/Resources/app.asar/main/zettlr.js:302:12)
    at Zettlr.handleAddRoots (/Applications/Zettlr.app/Contents/Resources/app.asar/main/zettlr.js:400:25)
    at App.<anonymous> (/Applications/Zettlr.app/Contents/Resources/app.asar/main.js:96:12)
    at App.emit (events.js:188:13)
```

## Platform
 - OS X 
 - Zettlr Version 1.2.1

**Comment by nathanlesage** [comment]
Please update to the newest version of Zettlr to verify that the bug still persists!

**Comment by dometto** [comment]
Sorry, I thought I'd seen an "You're on the latest version of Zettlr" message. Can't reproduce on v1.2.3

**Comment by nathanlesage** [comment]
Alright! But the update notifier did work, did it …? Because if not you might just've found another bug =D

**Comment by dometto** [comment]
Well, I certainly do the see the update notifier when I run Zettlr now! I just replaced the old version so can't see what happens when I run that now. :)
