### ISSUE TITLE
Cannot start latest develop TypeError: Cannot read property 'parse' of undefined

### ISSUE THREAD

**Issue by cskeogh** [Zettlr/Zettlr#1851]
## Description

Cannot run latest develop `TypeError: Cannot read property 'parse' of undefined`

## Reproducing

``` bash
$ git clone https://github.com/Zettlr/Zettlr.git
$ cd Zettlr
$ yarn install
$ cd source
$ yarn install
$ cd ..
$ yarn start
```

```
yarn run v1.22.10
$ electron-forge start
✔ Checking your system
✔ Locating Application
✔ Preparing native dependencies
✔ Compiling Main Process Code
✔ Launch Dev Servers
✔ Compiling Preload Scripts
✔ Launching Application


Webpack Output Available: http://localhost:9000

[14:12:58] こんにちは！ Booting Zettlr at Fri Apr 02 2021 14:12:58 GMT+1030 (Australian Central Daylight Time).
[14:12:58] Performing environment check ...
[14:12:58] [Application] App is unpackaged, and Pandoc has been found in the resources directory: /home/craig/Zettlr/resources/pandoc
[14:12:58] Environment check complete.
[14:12:58] Registering custom protocol safe-file
[14:12:58] Log provider booting up ...
[14:12:58] Config provider booting up ...
TypeError: Cannot read property 'parse' of undefined
    at Object.getConfigTemplate [as default] (/home/craig/Zettlr/.webpack/main/index.js:131649:38)
    at new ConfigProvider (/home/craig/Zettlr/.webpack/main/index.js:133649:52)
    at Object.bootApplication (/home/craig/Zettlr/.webpack/main/index.js:131115:22)
Done in 19.25s.
```

## Expected behaviour
Zettlr starts

## Platform
- Windows 10. Same error occurs on Fedora 33
- Zettlr Version: develop 13e533b7106205c70b1f3c3243cd16978d44ce54

**Comment by nathanlesage** [comment]
Fixed by merging #1852
