### ISSUE TITLE
Invalid dependencies have been reported by plugins or loaders for this module. All reported dependencies need to be absolute paths

### ISSUE THREAD

**Issue by cskeogh** [Zettlr/Zettlr#2029]
## Description
Zettlr displays error:

```
WARNING in ./source/common/i18n.js
Invalid dependencies have been reported by plugins or loaders for this module. All reported dependencies need to be absolute paths.
Invalid dependencies may lead to broken watching and caching.
As best effort we try to convert all invalid values to absolute paths and converting globs into context dependencies, but this is deprecated behavior.
Loaders: Pass absolute paths to this.addDependency (existing files), this.addMissingDependency (not existing files), and this.addContextDependency (directories).
Plugins: Pass absolute paths to fileDependencies (existing files), missingDependencies (not existing 
files), and contextDependencies (directories).
Globs: They are not supported. Pass absolute path to the directory as context dependencies.
The following invalid values have been reported:
 * "C:/Users/craig/Zettlr/source/common/lang/ar-AR.json"
 * "C:/Users/craig/Zettlr/source/common/lang/ca-CA.json"
 * "C:/Users/craig/Zettlr/source/common/lang/cs-CZ.json"
 * and more ...
 @ ./source/common/modules/window-register/register-default-context.ts 4:15-36
 @ ./source/common/modules/window-register/index.ts 8:51-88
 @ ./source/win-main/index.ts 19:42-86

1 warning has detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

webpack 5.37.1 compiled with 1 warning in 12727 ms
```

## Reproducing
Start Zettlr. Error occurs on startup.

## Expected behaviour
Zettlr starts without error

## Platform
 - OS and version: Windows. Does not happen on Linux.
 - Zettlr Version: develop e358a054c7dc3e8edd431b21ea61f550dcff9e69

## Additional information
Introduced in 5061aca4041ca7ab2496401cd41553885bd2f8a3

**Comment by nathanlesage** [comment]
Would you mind running that command using the `--stats-error-details` flag? Maybe that'll spit out more info. Other than that, I'm also not experiencing this issue on macOS, so it might have to do either with git (CRLF-issues?) or Webpack itself (maybe there's something on the web on this?)

**Comment by cskeogh** [comment]
I added the following in `webpack.main.config.js`:

```javascript
module.exports = {
  stats: {
    errors: true,
    errorStack: true,
    errorDetails: true, // --display-error-details
  },
```

The error is:

```
[16:33:24] [Update Provider] Update available: v1.8.9
(node:19252) ExtensionLoadWarning: Warnings loading extension at C:\Users\craig\AppData\Roaming\Zettlr\extensions\nhdogjmejiglipccpnnnanhbledajbpd:
  Unrecognized manifest key 'browser_action'.
  Unrecognized manifest key 'update_url'.
  Permission 'contextMenus' is unknown or URL pattern is malformed.
  Cannot load extension with file or directory name _metadata. Filenames starting with "_" are reserved for use by the system.

(Use `electron --trace-warnings ...` to show where the warning was created)
[16:33:24] Added DevTools extension:  Vue.js devtools
| Compiling Renderer Code137 assets
runtime modules 334 KiB 158 modules
orphan modules 525 bytes [orphan] 2 modules
modules by path ./node_modules/ 7.22 MiB
  javascript modules 7.19 MiB 1242 modules
  json modules 30 KiB
    ./node_modules/entities/lib/maps/entities.json 28.4 KiB [built] [code generated]
    ./node_modules/entities/lib/maps/legacy.json 1.24 KiB [built] [code generated]
    ./node_modules/entities/lib/maps/xml.json 62 bytes [built] [code generated]
    ./node_modules/entities/lib/maps/decode.json 308 bytes [built] [code generated]
modules by path ./source/ 2.07 MiB 729 modules
18 modules

WARNING in ./source/common/i18n.js
Invalid dependencies have been reported by plugins or loaders for this module. All reported dependencies need to be absolute paths.
Invalid dependencies may lead to broken watching and caching.
As best effort we try to convert all invalid values to absolute paths and converting globs into context dependencies, but this is deprecated behavior.
Loaders: Pass absolute paths to this.addDependency (existing files), this.addMissingDependency (not existing files), and this.addContextDependency (directories).
Plugins: Pass absolute paths to fileDependencies (existing files), missingDependencies (not existing files), and contextDependencies (directories).
Globs: They are not supported. Pass absolute path to the directory as context dependencies.
The following invalid values have been reported:
 * "C:/Users/craig/Zettlr/source/common/lang/ar-AR.json"
 * "C:/Users/craig/Zettlr/source/common/lang/ca-CA.json"
 * "C:/Users/craig/Zettlr/source/common/lang/cs-CZ.json"
 * and more ...
 * "C:/Users/craig/Zettlr/source/common/lang/da-DA.json"
 * "C:/Users/craig/Zettlr/source/common/lang/de-DE.json"
 * "C:/Users/craig/Zettlr/source/common/lang/en-GB.json"
 * "C:/Users/craig/Zettlr/source/common/lang/en-US.json"
 * "C:/Users/craig/Zettlr/source/common/lang/es-ES.json"
 * "C:/Users/craig/Zettlr/source/common/lang/eu-EU.json"
 * "C:/Users/craig/Zettlr/source/common/lang/fi-FI.json"
 * "C:/Users/craig/Zettlr/source/common/lang/fr-FR.json"
 * "C:/Users/craig/Zettlr/source/common/lang/hu-HU.json"
 * "C:/Users/craig/Zettlr/source/common/lang/id-ID.json"
 * "C:/Users/craig/Zettlr/source/common/lang/it-IT.json"
 * "C:/Users/craig/Zettlr/source/common/lang/ja-JP.json"
 * "C:/Users/craig/Zettlr/source/common/lang/ko-KO.json"
 * "C:/Users/craig/Zettlr/source/common/lang/nl-NL.json"
 * "C:/Users/craig/Zettlr/source/common/lang/pl-PL.json"
 * "C:/Users/craig/Zettlr/source/common/lang/pt-BR.json"
 * "C:/Users/craig/Zettlr/source/common/lang/pt-PT.json"
 * "C:/Users/craig/Zettlr/source/common/lang/ro-RO.json"
 * "C:/Users/craig/Zettlr/source/common/lang/ru-RU.json"
 * "C:/Users/craig/Zettlr/source/common/lang/tr-TR.json"
 * "C:/Users/craig/Zettlr/source/common/lang/uk-UK.json"
 * "C:/Users/craig/Zettlr/source/common/lang/zh-CN.json"
InvalidDependenciesModuleWarning: Invalid dependencies have been reported by plugins or loaders for this module. All reported dependencies need to be absolute paths.
Invalid dependencies may lead to broken watching and caching.
As best effort we try to convert all invalid values to absolute paths and converting globs into context dependencies, but this is deprecated behavior.
Loaders: Pass absolute paths to this.addDependency (existing files), this.addMissingDependency (not existing files), and this.addContextDependency (directories).
Plugins: Pass absolute paths to fileDependencies (existing files), missingDependencies (not existing files), and contextDependencies (directories).
Globs: They are not supported. Pass absolute path to the directory as context dependencies.
The following invalid values have been reported:
 * "C:/Users/craig/Zettlr/source/common/lang/ar-AR.json"
 * "C:/Users/craig/Zettlr/source/common/lang/ca-CA.json"
 * "C:/Users/craig/Zettlr/source/common/lang/cs-CZ.json"
 * and more ...
    at handleBuildDone (C:\Users\craig\Zettlr\node_modules\webpack\lib\NormalModule.js:979:7)
    at handleParseResult (C:\Users\craig\Zettlr\node_modules\webpack\lib\NormalModule.js:935:12)
    at C:\Users\craig\Zettlr\node_modules\webpack\lib\NormalModule.js:1025:4
    at processResult (C:\Users\craig\Zettlr\node_modules\webpack\lib\NormalModule.js:742:11)
    at C:\Users\craig\Zettlr\node_modules\webpack\lib\NormalModule.js:806:5
    at C:\Users\craig\Zettlr\node_modules\loader-runner\lib\LoaderRunner.js:406:3
    at iterateNormalLoaders (C:\Users\craig\Zettlr\node_modules\loader-runner\lib\LoaderRunner.js:232:10)
    at iterateNormalLoaders (C:\Users\craig\Zettlr\node_modules\loader-runner\lib\LoaderRunner.js:239:10)
    at C:\Users\craig\Zettlr\node_modules\loader-runner\lib\LoaderRunner.js:254:3
    at Object.context.callback (C:\Users\craig\Zettlr\node_modules\loader-runner\lib\LoaderRunner.js:124:13)
    at C:\Users\craig\Zettlr\node_modules\@vercel\webpack-asset-relocator-loader\dist\index.js:29019:10
 @ ./node_modules/@vercel/webpack-asset-relocator-loader/dist/index.js??clonedRuleSet-2[0].rules[0].use!./node_modules/vue-loader/lib/index.js??vue-loader-options!./source/win-main/App.vue?vue&type=script&lang=js& 69:0-38 156:14-19 165:17-22 169:14-19 196:17-22 202:17-22 208:17-22 214:17-22 230:17-22 240:17-22 246:17-22 252:17-22 258:17-22 264:17-22 270:17-22 276:17-22 282:17-22 288:17-22 294:17-22 300:17-22 306:17-22 320:17-22
 @ ./source/win-main/App.vue?vue&type=script&lang=js& 1:0-223 1:239-242 1:244-464 1:244-464
 @ ./source/win-main/App.vue 2:0-55 3:0-50 3:0-50 10:2-8
 @ ./source/win-main/index.ts 22:34-54

webpack 5.37.1 compiled with 1 warning in 20419 ms
✔ Compiling Renderer Code
No issues found.
- Compiling Renderer Code[16:33:42] [R] [Main Window] [HMR] Waiting for update signal from WDS... (index.js:202334)
\ Compiling Renderer Code[16:33:43] [R] [Main Window] File allocation: 0.004150390625 ms (index.js:181417)
[16:33:43] [R] [Main Window] You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html (index.js:196247)
[16:33:43] [R] [Main Window] [webpack-dev-server] Hot Module Replacement enabled. (index.js:201097)
[16:33:43] [R] [Main Window] [webpack-dev-server] Live Reloading enabled. (index.js:201097)
[16:33:43] [R] [Main Window] [webpack-dev-server] Warnings while compiling. (index.js:201102)
[16:33:43] [R] [Main Window] [webpack-dev-server] Invalid dependencies have been reported by plugins or loaders for this module. All reported dependencies need to be absolute paths.
Invalid dependencies may lead to broken watching and caching.
As best effort we try to convert all invalid values to absolute paths and converting globs into context dependencies, but this is deprecated behavior.
Loaders: Pass absolute paths to this.addDependency (existing files), this.addMissingDependency (not existing files), and this.addContextDependency (directories).
Plugins: Pass absolute paths to fileDependencies (existing files), missingDependencies (not existing files), and contextDependencies (directories).
Globs: They are not supported. Pass absolute path to the directory as context dependencies.
The following invalid values have been reported:
 * "C:/Users/craig/Zettlr/source/common/lang/ar-AR.json"
 * "C:/Users/craig/Zettlr/source/common/lang/ca-CA.json"
 * "C:/Users/craig/Zettlr/source/common/lang/cs-CZ.json"
 * and more ... (index.js:201102)
```

**Comment by cskeogh** [comment]
Perhaps `/` is causing problems on Windows? See https://github.com/webpack/webpack/issues/10980#issuecomment-636988269   
But I can't work out where the string `"C:/Users/craig/Zettlr/source/common/lang/ar-AR.json"` originates to test my idea.

**Comment by nathanlesage** [comment]
> But I can't work out where the string "C:/Users/craig/Zettlr/source/common/lang/ar-AR.json" originates to test my idea.

Very likely this file: https://github.com/Zettlr/Zettlr/blob/develop/webpack.main.config.js

Specifically, we use the Copy plugin to copy over static files, among of which are the language files. Might be a problem with the plugin …?

**Comment by cskeogh** [comment]
The warning was introducted by https://github.com/webpack/webpack/commit/09862aacf87f53168c0b490b68db4cc3b5abc9c8

Line 828 of https://github.com/webpack/webpack/commit/09862aacf87f53168c0b490b68db4cc3b5abc9c8 the `checkDependencies` checks paths against `const ABSOLUTE_PATH_REGEX = /^([a-zA-Z]:\\|\\\\|\/)/;`.

The following paths are checked, in order. They all pass:
```
"C:\\Users\\craig\\Zettlr\\source\\main.ts"
"C:\\Users\\craig\\Zettlr\\source\\app\\lifecycle.ts"
"C:\\Users\\craig\\Zettlr\\source\\main\\zettlr.ts"
```
... and later ... the first to fail:
```
"C:/Users/craig/Zettlr/source/common/lang/ar-AR.json"
```
Note the `/` vs the `\\`

I think it's the `@vercel/webpack-asset-relocator-loader` responsible for this path.
https://github.com/Zettlr/Zettlr/blob/7d7028947c68095f43757b550ef0dfae37ca8019/webpack.rules.js#L11

Setting debugLog as follows:

```javascript
      loader: '@vercel/webpack-asset-relocator-loader',
      options: {
        outputAssetBase: 'native_modules',
        debugLog: true,
```

The following is logged:
```
Emitting C:\Users\craig\Zettlr\source\common\lang\en-US.json for static use in module C:\Users\craig\Zettlr\source\common\i18n.js
Emitting directory C:\Users\craig\Zettlr\source\common\lang/**/* for static use in module C:\Users\craig\Zettlr\source\common\i18n.js
Emitting directory C:\Users\craig\Zettlr\source\common\lang/**/* for static use in module C:\Users\craig\Zettlr\source\common\i18n.js
```

However, I don't know how to solve the problem.

**Comment by nathanlesage** [comment]
Mh, I knew it had to do something with the assets copying process. But other than that I also don't know how to solve it, and can't really dig into it right now …

**Comment by cskeogh** [comment]
Fixed by @nathanlesage in today's commits. Thank you!

**Comment by cangSDARM** [comment]
How is this achieved? That commit is too long to read
