### ISSUE TITLE
Cannot run the devel branch anymore

### ISSUE THREAD

**Issue by ploum** [Zettlr/Zettlr#220]
Just did a git pull this morning. Here's the result :

App threw an error during load
Error: Cannot find module 'astrocite-bibtex'
    at Module._resolveFilename (internal/modules/cjs/loader.js:610:15)
    at Function.Module._resolveFilename (/Users/ploum/zettlr/Zettlr/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.Module._load (internal/modules/cjs/loader.js:539:25)
    at Module.require (internal/modules/cjs/loader.js:664:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/ploum/zettlr/Zettlr/source/main/zettlr-citeproc.js:25:22)
    at Object.<anonymous> (/Users/ploum/zettlr/Zettlr/source/main/zettlr-citeproc.js:373:3)
    at Module._compile (internal/modules/cjs/loader.js:729:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:741:10)
    at Module.load (internal/modules/cjs/loader.js:627:32)

**Comment by nathanlesage** [comment]
Yep, I've added astrocite as a new dependency, it's a library for converting BibTex to CSL JSON; you just need to re-install to pull all modules Zettlr uses:

```
$ yarn install --frozen-lockfile
$ npm install (if you're using NPM and not Yarn)
```

Then it'll work again.
