### ISSUE TITLE
[DEVELOP] Bumpy window state logic

### ISSUE THREAD

**Issue by nathanlesage** [Zettlr/Zettlr#2200]
Some people have already complained that the window state logic is weird and I know that whenever I close the main window and re-open it in the same instance, it opens in a different place and size. Now I've had the first accident that a window state caused an actual error.

I know the whole window state management is a little bit bodgy, so if someone has the chance to take a look, that'd be great! Plus it might be possible to combine that with the service provider for various settings (i.e. those that are not strictly speaking config but still something we might want to cache), see this issue: #1039

**Comment by nathanlesage** [comment]
Pushing this one a tad more up, since it seems that the window state logic is now producing more and more errors. The one in #2547 happened to me yesterday as well.

**Comment by dave-kennedy** [comment]
Is this related?

![image](https://user-images.githubusercontent.com/13735532/136208615-711a0055-ccee-45ef-b906-0becddb2e775.png)

This occurs whenever I go to Zettlr > Preferences on macOS.

Here's the rest of the error:

```
Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from 
at t.default (/Users/dave.kennedy/Applications/Zettlr.app/Contents/Resources/app.asar/.webpack/main/index.js:2:1616046)
at D._retrieveWindowPosition (/Users/dave.kennedy/Applications/Zettlr.app/Contents/Resources/app.asar/.webpack/main/index.js:2:1609342)
at D.showPreferences (/Users/dave.kennedy/Applications/Zettlr.app/Contents/Resources/app.asar/.webpack/main/index.js:2:1611932)
at Object.showPreferences (/Users/dave.kennedy/Applications/Zettlr.app/Contents/Resources/app.asar/.webpack/main/index.js:2:1617992)
at click (/Users/dave.kennedy/Applications/Zettlr.app/Contents/Resources/app.asar/.webpack/main/index.js:2:1406048)
at MenuItem.click (electron/js2c/browser_init.js:73:1742)
at Object.a._executeCommand (electron/js2c/browser_init.js:81:2492)
```

Running version 2.0.0-beta.5 on macOS 11.6.

**Comment by nathanlesage** [comment]
Arghh, yeah the thing is this will make it in 2.0, but I don't have much time :(

**Comment by dave-kennedy** [comment]
> Arghh, yeah the thing is this will make it in 2.0, but I don't have much time :(

I feel your pain. This is the trouble with passion projects.
