### ISSUE TITLE
[Bug] yarn start fails on current develop

### ISSUE THREAD

**Issue by Johennes** [Zettlr/Zettlr#2356]
### Description

I'm not sure if this is an issue in my local environment but on the current `develop` branch `yarn start` fails with a runtime error for me.

```
$ yarn start
...
(Use `electron --trace-warnings ...` to show where the warning was created)
[09:34:21] こんにちは！ Booting Zettlr at Wed Aug 25 2021 09:34:21 GMT+0200 (Central European Summer Time).
[09:34:21] Performing environment check ...
[09:34:21] [Application] App is unpackaged, and Pandoc has been found in the resources directory: /home/jm/Code/forks/Zettlr/resources/pandoc
[09:34:21] Added DevTools extension:  Vue.js devtools
[09:34:21] Environment check complete.
[09:34:21] Registering custom protocol safe-file
[09:34:21] Log provider booting up ...
[09:34:21] Config provider booting up ...
[09:34:21] [Config Provider] Loading configuration file from /home/jm/.config/Zettlr/config.json ...
[09:34:21] [Config Provider] Successfully loaded configuration
[09:34:21] Appearance provider booting up ...
[09:34:21] Assets provider starting up ...
[09:34:21] Citeproc provider booting up ...
[09:34:21] [Citeproc Provider] Loading CSL locale file at /home/jm/Code/forks/Zettlr/.webpack/main/assets/csl-locales/locales-en-US.xml ...
[09:34:21] [Citeproc Provider] Loading CSL locale file at /home/jm/Code/forks/Zettlr/.webpack/main/assets/csl-locales/locales-en-GB.xml ...
[09:34:22] Dictionary provider booting up ...
[09:34:22] Menu provider booting up ...
TypeError: Cannot read property 'on' of undefined
    at new MenuProvider (/home/jm/Code/forks/Zettlr/.webpack/main/index.js:118468:31)
    at Object.bootApplication (/home/jm/Code/forks/Zettlr/.webpack/main/index.js:114468:20)
Done in 96.54s.
```

After commenting `global.recentDocs.on('update', () => { this.set() })` in `menu-provider.ts` the app launches.

### Reproducing

Clone the repo, run `yarn install --frozen-lockfile` followed by `yarn start`.

### Zettlr Version

Right off the develop branch

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

KDN Neon / Ubuntu 20.04.2 LTS

**Comment by nathanlesage** [comment]
Pretty sure this is the culprit: https://github.com/Zettlr/Zettlr/commit/fdd09965963a38ee2173a87c7091183eda13aa30

**Comment by Johennes** [comment]
Light speed! :pray:

**Comment by nathanlesage** [comment]
⚡
