### ISSUE TITLE
[Bug] Help/About Zettlr produces an error message

### ISSUE THREAD

**Issue by chchen2021** [Zettlr/Zettlr#2547]
### Description

On macOS Big Sur, the menu item `Help/About Zettlr` produces an error message entitled "A JavaScript error occurred in the main process". In contrast, `Zettlr/About Zettlr` produces the expected version and copyright information. 

### Reproducing

Click the menu item `Help/About Zettlr`, and the following message will show up:

```
**A JavaScript error occurred in the main process**
Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from 
at t.default (/Applications/Zettlr.app/Contents/Resources/app.asar/.webpack/main/index.js:2:1616046)
at D._retrieveWindowPosition (/Applications/Zettlr.app/Contents/Resources/app.asar/.webpack/main/index.js:2:1609342)
at D.showAboutWindow (/Applications/Zettlr.app/Contents/Resources/app.asar/.webpack/main/index.js:2:1612250)
at Object.showAboutWindow (/Applications/Zettlr.app/Contents/Resources/app.asar/.webpack/main/index.js:2:1618052)
at click (/Applications/Zettlr.app/Contents/Resources/app.asar/.webpack/main/index.js:2:1415778)
at MenuItem.click (electron/js2c/browser_init.js:73:1742)
at Object.a._executeCommand (electron/js2c/browser_init.js:81:2492)
```

### Zettlr Version

Beta (if applicable)

### Specify version

Version 2.0.0-beta.5

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

11.6

### Additional Information

The same error message showed up on Version 2.0.0-beta.4. 

Recommendation: remove the "About Zettlr" under "Help", since there is already one under "Zettlr". The first time when I encountered this error, I thought I had a system crash.

**Comment by chchen2021** [comment]
After a couple of macOS restarts, the "Help/About Zettlr" is now showing the correct information window. Not sure if the restart solved the problem. 

I now see there are two "About Zettlr". The one under "Help" has much more information.

**Comment by nathanlesage** [comment]
> I now see there are two "About Zettlr". The one under "Help" has much more information.

Yeah one is the built-in one, the other one is a custom dialog. The `window_position.json` (in Library/Application Support/Zettlr) is the culprit. Deleting it should work.

Furthermore, closing in favor of #2200
