### ISSUE TITLE
nightly on intel mac not opening: A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by foss-** [Zettlr/Zettlr#4068]
### Description

macOS 13.1, intel mac
Zettlr 3.0.0b1, Nightly from 2023-01-17 for intel mac does not open with following error:

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: dlopen(/Applications/Zettlr.app/Contents/Resources/app.asar.unpacked/.webpack/main/native_modules/build/Release/Nodehun.node, 0x0001): tried: '/Applications/Zettlr.app/Contents/Resources/app.asar.unpacked/.webpack/main/native_modules/build/Release/Nodehun.node' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h' or 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Zettlr.app/Contents/Resources/app.asar.unpacked/.webpack/main/native_modules/build/Release/Nodehun.node' (no such file), '/Applications/Zettlr.app/Contents/Resources/app.asar.unpacked/.webpack/main/native_modules/build/Release/Nodehun.node' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h' or 'x86_64'))
at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
at Module._extensions..node (node:internal/modules/cjs/loader:1226:18)
at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)
at Module.load (node:internal/modules/cjs/loader:1011:32)
at Module._load (node:internal/modules/cjs/loader:846:12)
at f._load (node:electron/js2c/asar_bundle:2:13328)
at Module.require (node:internal/modules/cjs/loader:1035:19)
at require (node:internal/modules/cjs/helpers:102:18)
at 19572 (/Applications/Zettlr.app/Contents/Resources/app.asar/.webpack/main/index.js:2:1153497)
at r (/Applications/Zettlr.app/Contents/Resources/app.asar/.webpack/main/index.js:2:2154532)
```

### Reproducing

Open nightly

### Zettlr Version

Nightly

### Specify version

2023-01-17

### Installation Method

From the Website or GitHub

### Your Platform

macOS

### Architecture

Intel 64bit

### Operating System Version

macOS 13.1

**Comment by StefanoCecere** [comment]
also latest beta doesn't work on m1
(I was about to test latest nightly but you already did=

**Comment by nathanlesage** [comment]
@foss- Would you mind checking the new beta, if that one now works?

**Comment by foss-** [comment]
@nathanlesage Sure. Sadly this is persisting with 3.0.0b1:

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: dlopen(/Applications/Zettlr.app/Contents/Resources/app.asar.unpacked/.webpack/main/native_modules/build/Release/Nodehun.node, 0x0001): tried: '/Applications/Zettlr.app/Contents/Resources/app.asar.unpacked/.webpack/main/native_modules/build/Release/Nodehun.node' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h' or 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Zettlr.app/Contents/Resources/app.asar.unpacked/.webpack/main/native_modules/build/Release/Nodehun.node' (no such file), '/Applications/Zettlr.app/Contents/Resources/app.asar.unpacked/.webpack/main/native_modules/build/Release/Nodehun.node' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h' or 'x86_64'))
at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
at Module._extensions..node (node:internal/modules/cjs/loader:1226:18)
at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)
at Module.load (node:internal/modules/cjs/loader:1011:32)
at Module._load (node:internal/modules/cjs/loader:846:12)
at f._load (node:electron/js2c/asar_bundle:2:13328)
at Module.require (node:internal/modules/cjs/loader:1035:19)
at require (node:internal/modules/cjs/helpers:102:18)
at 19572 (/Applications/Zettlr.app/Contents/Resources/app.asar/.webpack/main/index.js:2:1153497)
at r (/Applications/Zettlr.app/Contents/Resources/app.asar/.webpack/main/
```

**Comment by nathanlesage** [comment]
Dammit. I'll have a look.

**Comment by nathanlesage** [comment]
@halloichbingunnar – you also have an Intel Mac, right? For you the beta works, if I read your last comment correctly, is that so?

**Comment by halloichbingunnar** [comment]
yes! works fine for me

**Comment by halloichbingunnar** [comment]
apologies, I had the beta, not the latest nightly. nightly doesn't start, javascript error

**Comment by WolfgangDpunkt** [comment]
Same error here, on Intel Mac with macOS Catalina.
Nightly and beta1.

`Uncaught Exception:
Error: dlopen(/Applications/Zettlr.app/Contents/Resources/app.asar.unpacked/.webpack/main/native_modules/build/Release/Nodehun.node, 1): no suitable image found.  Did find:
	/Applications/Zettlr.app/Contents/Resources/app.asar.unpacked/.webpack/main/native_modules/build/Release/Nodehun.node: mach-o, but wrong architecture
	/Applications/Zettlr.app/Contents/Resources/app.asar.unpacked/.webpack/main/native_modules/build/Release/Nodehun.node: mach-o, but wrong architecture
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1226:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at f._load (node:electron/js2c/asar_bundle:2:13328)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at 19572 (/Applications/Zettlr.app/Contents/Resources/app.asar/.webpack/main/index.js:2:1153497)
    at r (/Applications/Zettlr.app/Contents/Resources/app.asar/.webpack/main/index.js:2:2156727)`

**Comment by mattfarina** [comment]
In the error I got on the beta.1 it said...

> mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h' or 'x86_64'

My guess is that some thing(s) were built for the wrong architecture.

**Comment by foss-** [comment]
The Electron Forge issue causing these headaches is https://github.com/electron/forge/issues/3114

**Comment by nathanlesage** [comment]
@foss- @mattfarina @WolfgangDpunkt @halloichbingunnar I have done some violence to the build script, would you mind trying the files on https://nightly.zettlr.com ? The ARM64 file works splendid, so we now just have to verify the Intel file, but it should in theory work now.

**Comment by halloichbingunnar** [comment]
works for me! thank you very much!

**Comment by nathanlesage** [comment]
Amazing, thanks for confirming! If anyone of the rest experiences problems, please feel free to ping here, but I desperately need to close an issue, GitHub Actions has been killing me today …

**Comment by LaPingvino** [comment]
@nathanlesage I have this issue on the nightly with Linux arm64, I suppose the lesser tested version...
