### ISSUE TITLE
x64 version of 3.0.0-beta1 will not open on Intel Mac upgrading from 2.3.0

### ISSUE THREAD

**Issue by jd101k2000** [Zettlr/Zettlr#4120]
### Description

I have downloaded Zettlr-3.0.0-beta.1-x64.dmg.
I have installed it on an Intel Mac with macOS 12.6.3
When I try to run Zettlr I get the error at the bottom of this message.

At first I thought, 'have I downloaded the ARM64 version by mistake'? No - definitely have the correct version.

## Here are the details of my Mac:

 Model Name:	Mac mini
 Model Identifier:	Macmini8,1
 Processor Name:	6-Core Intel Core i7
 Processor Speed:	3.2 GHz
 Number of Processors:	1
 Total Number of Cores:	6
 L2 Cache (per Core):	256 KB
 L3 Cache:	12 MB
 Hyper-Threading Technology:	Enabled
 Memory:	32 GB

## Error follows:

A JavaScript error occurred in the main process

Uncaught Exception:
Error: dlopen(/Applications/Zettlr.app/Contents/Resources/app.asar.unpacked/.webpack/main/native_modules/build/Release/Nodehun.node, 0x0001): tried: '/Applications/Zettlr.app/Contents/Resources/app.asar.unpacked/.webpack/main/native_modules/build/Release/Nodehun.node' (mach-o file, but is an incompatible architecture (have (arm64), need (x86_64h)))
at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
at Module._extensions..node (node:internal/modules/cjs/loader:1226:18)
at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)
at Module.load (node:internal/modules/cjs/loader:1011:32)
at Module._load (node:internal/modules/cjs/loader:846:12)
at f._load (node:electron/js2c/asar_bundle:2:13328)
at Module.require (node:internal/modules/cjs/loader:1035:19)
at require (node:internal/modules/cjs/helpers:102:18)
at 19572 (/Applications/Zettlr.app/Contents/Resources/app.asar/.webpack/main/index.js:2:1153497)
at r (/Applications/Zettlr.app/Contents/Resources/app.asar/.webpack/main/index.js:2:2156778)

### Reproducing

Idownload Zettlr-3.0.0-beta.1-x64.dmg.
Install it on an Intel Mac with macOS 12.6.3
run Zettlr

### Zettlr Version

Beta (if applicable)

### Specify version

3.0.0-beta.1-x64

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

12.6.3

### Additional Information

Uncaught Exception:
Error: dlopen(/Applications/Zettlr.app/Contents/Resources/app.asar.unpacked/.webpack/main/native_modules/build/Release/Nodehun.node, 0x0001): tried: '/Applications/Zettlr.app/Contents/Resources/app.asar.unpacked/.webpack/main/native_modules/build/Release/Nodehun.node' (mach-o file, but is an incompatible architecture (have (arm64), need (x86_64h)))
at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
at Module._extensions..node (node:internal/modules/cjs/loader:1226:18)
at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)
at Module.load (node:internal/modules/cjs/loader:1011:32)
at Module._load (node:internal/modules/cjs/loader:846:12)
at f._load (node:electron/js2c/asar_bundle:2:13328)
at Module.require (node:internal/modules/cjs/loader:1035:19)
at require (node:internal/modules/cjs/helpers:102:18)
at 19572 (/Applications/Zettlr.app/Contents/Resources/app.asar/.webpack/main/index.js:2:1153497)
at r (/Applications/Zettlr.app/Contents/Resources/app.asar/.webpack/main/index.js:2:2156778)

**Comment by nathanlesage** [comment]
This is known and fortunately already fixed. Please download the current nightly from https://nightly.zettlr.com !
