### ISSUE TITLE
Save file stops working

### ISSUE THREAD

**Issue by antaln** [Zettlr/Zettlr#4878]
### Description

Using Zettlr 3.0.3 on Windows 10 x64. My workspace is committed into git. If a git pull gets multiple changes while Zettlr is open, the file tree is properly updated, but saving silently fails. Stderr of zettlr.exe shows the following error:

```
Error occurred in handler for 'documents-authority': RangeError: Applying change set to a document with the wrong length
    at x.apply (<REDACTED>\Zettlr\resources\app.asar\.webpack\main\index.js:2:2701340)
    at w.pushUpdates (<REDACTED>\Zettlr\resources\app.asar\.webpack\main\index.js:2:1980734)
    at <REDACTED>\Zettlr\resources\app.asar\.webpack\main\index.js:2:1974927
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:89107)
    at WebContents.emit (node:events:513:28)
```

After this error is reported, all file saving stops working until Zettlr is restarted. The condition is semi-silent: if one makes changes to a file in Zettlr, no asterisk is shown in the title in the tab bar, but there is no error reported of any kind in the UI. The RangeError error report is only visible in the log/stderr of Zettlr.

### Reproducing

1. Close Zettlr
2. Modify a few files in the workspace
3. Do `git stash`
4. Open Zettlr
5. Do `git stash apply` to apply changes from 2
6. Edit and attempt to save the document.

Repro uses git stash for local, but this would commonly occur with regular git workflow where changes are pushed from different authors or hosts, and `git pull` fetches and merges them into your clone all at once). In that workflow, step 2 is replaced with "modify + commit + push from a separate source" and step 5 with `git pull`, with the same outcome.

### Zettlr Version

Stable (most recent version)

### Specify version

3.0.3

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
Thank you for this very informative issue. It appears there is some choking happening under the hood, where the service provider just overwrites the document in the background *despite there being unsaved changes*, which then means that the changes of the editor cannot be applied to the document. That shouldn't happen, for sure.

Quick follow up before I try to repro this on the current develop branch: Is a minimal reproducible example to simply modify a document in Zettlr without saving, then modifying it externally, and then trying to save? Or does this approach work fine?

Also, if you're willing, feel free to try to reproduce this directly on the coming nightly on Monday, which implements a fair amount of changes to the external change management. If not, I can absolutely understand.

**Comment by antaln** [comment]
> Quick follow up before I try to repro this on the current develop branch: Is a minimal reproducible example to simply modify a document in Zettlr without saving, then modifying it externally, and then trying to save? Or does this approach work fine?

That approach works fine - it correctly detects that file was modified outside, and offers a dialog to either reload the file or keep the changes.

> Also, if you're willing, feel free to try to reproduce this directly on the coming nightly on Monday, which implements a fair amount of changes to the external change management. If not, I can absolutely understand.

I will certainly try and let you know.

**Comment by nathanlesage** [comment]
Hi, I just rediscovered this issue, and I remember that I fixed that particular issue in recent weeks!
