### ISSUE TITLE
Ctrl+W on unsaved notification produces an exception

### ISSUE THREAD

**Issue by Zverik** [Zettlr/Zettlr#930]
1. Wait until you've got a notification (I had "replace file" from #746)
2. Press Ctrl+W / Cmd+W

Expected: nothing

Got:

```
Uncaught Exception:
TypeError: Cannot read property 'close' of null
    at ZettlrIPC.send (/Applications/Zettlr.app/Contents/Resources/app.asar/main/zettlr-ipc.js:147:39)
    at Object.send (/Applications/Zettlr.app/Contents/Resources/app.asar/main/zettlr-ipc.js:106:34)
    at builtItem.click (/Applications/Zettlr.app/Contents/Resources/app.asar/main/zettlr-menu.js:113:22)
    at MenuItem.click (electron/js2c/browser_init.js:1552:9)
    at Function.executeCommand (electron/js2c/browser_init.js:1813:13)
```

_1.7.0-beta.11 on macOS 10.14.5_

**Comment by nathanlesage** [comment]
That is interesting behaviour o_O

**Comment by nathanlesage** [comment]
Let's see where we can get simply silencing the complaints by the main process 🙃
